# 玄关灯光自动化配置
# ========== 回家模式 - 开灯 ==========
- alias: 玄关 - 回家模式开灯
  id: light_entrance_home_mode
  mode: single
  description: 检测到home_state从off变为on时（回家），开启筒灯和氛围灯；18-24点之间延迟打开客厅灯带
  trigger:
    - platform: state
      entity_id: binary_sensor.home_state
      from: "off"
      to: "on"
      for:
        seconds: 1  # 确保状态稳定，避免误触发
  action:
    # 开启氛围灯
    - service: switch.turn_on
      target:
        entity_id: switch.giot_cn_1088542711_v6oodm_on_p_2_1
    # 并行执行筒灯和客厅灯带的等待和开启，失败互不影响
    - parallel:
        # 筒灯序列（等待设备可用后延迟1秒开启） 忽略,断电前开启状态
        # - sequence:
        #     - delay:
        #         seconds: 5
        #     - service: switch.turn_on
        #       target:
        #         entity_id: switch.linp_cn_1080373159_q3s2_on_p_3_1
        # 客厅灯带序列（仅在18-24点之间执行）
        - sequence:
            - condition: template
              value_template: "{{ now().hour >= 18 }}"
            # 等待设备可用（设备启动有延迟）
            - wait_template: "{{ states('switch.lumi_cn_551288517_acn032_on_p_4_1') not in ['unavailable', 'unknown'] }}"
              timeout: "00:00:30"
              continue_on_timeout: true
            # 设备可用后，再延迟3秒开灯
            - delay:
                seconds: 3
            # 打开客厅灯带
            - service: switch.turn_on
              target:
                entity_id: switch.lumi_cn_551288517_acn032_on_p_4_1

# 领普人体传感器3 - 移动检测自动控制灯光
# ========== 检测到移动 - 开灯（常规模式）==========
- alias: 玄关 - 检测到移动开灯
  id: light_entrance_motion_detected
  mode: single
  description: 检测到移动时，且有人在家时，开启筒灯和氛围灯
  trigger:
    - platform: state
      entity_id: event.linp_cn_blt_3_1kjgrp40ckg00_hs1bb2_motion_detected_e_2_1008
      not_from:
        - "unavailable"
        - "unknown"
      not_to:
        - "unavailable"
        - "unknown"
  condition:
    # 只在有人在家时触发（使用优化后的home_state传感器）
    - condition: state
      entity_id: binary_sensor.home_state
      state: "on"
  action:
    # 开启筒灯
    - service: switch.turn_on
      target:
        entity_id: switch.linp_cn_1080373159_q3s2_on_p_3_1
    # 开启氛围灯
    - service: switch.turn_on
      target:
        entity_id: switch.giot_cn_1088542711_v6oodm_on_p_2_1

# ========== 无移动15分钟 - 关筒灯 ==========
- alias: 玄关 - 无移动15分钟关筒灯
  id: light_entrance_no_motion_5min
  mode: single
  description: 无移动15分钟后，关闭筒灯
  trigger:
    - platform: state
      entity_id: sensor.linp_cn_blt_3_1kjgrp40ckg00_hs1bb2_no_motion_duration_p_2_1024
      to: "300"
      for: "00:10:00"
  condition:
    # 只在有人在家时触发（使用优化后的home_state传感器）
    - condition: state
      entity_id: binary_sensor.home_state
      state: "on"
    # 确保筒灯当前是开启状态
    - condition: state
      entity_id: switch.linp_cn_1080373159_q3s2_on_p_3_1
      state: 'on'
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.linp_cn_1080373159_q3s2_on_p_3_1

# ========== 无移动25分钟 - 关氛围灯 ==========
- alias: 玄关 - 无移动25分钟关氛围灯
  id: light_entrance_no_motion_10min
  mode: restart
  description: 无移动25分钟后（传感器维持在300超过300秒），关闭氛围灯
  trigger:
    - platform: state
      entity_id: sensor.linp_cn_blt_3_1kjgrp40ckg00_hs1bb2_no_motion_duration_p_2_1024
      to: "300"
      for: "00:20:00"
  condition:
    # 确保氛围灯当前是开启状态
    - condition: state
      entity_id: switch.giot_cn_1088542711_v6oodm_on_p_2_1
      state: 'on'
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.giot_cn_1088542711_v6oodm_on_p_2_1

