# nnleaf 灯光自动化配置
# ========== 单击按钮逻辑 - 切换开关状态 ==========
- alias: 书房 - nnleaf 切换开关状态
  id: light_nnleaf_switch_toggle
  trigger:
    - platform: state
      entity_id: event.090615_cn_blt_3_1gkcm9n48cc00_btsw1_click_e_2_1012
      not_from:
        - "unavailable"
        - "unknown"
      not_to:
        - "unavailable"
        - "unknown"
  action:
    # 检查两个灯的状态
    - variables:
        light1_state: "{{ states('light.nnleaf_cn_250150441_strips_s_2_light') }}"
        light2_state: "{{ states('switch.giot_cn_1099597079_v6oodm_on_p_2_1') }}"
        light1_is_on: "{{ light1_state == 'on' }}"
        light2_is_on: "{{ light2_state == 'on' }}"
        states_match: "{{ light1_is_on == light2_is_on }}"
    - choose:
        # 如果状态不一致，都切换为开
        - conditions:
            - condition: template
              value_template: "{{ not states_match }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.nnleaf_cn_250150441_strips_s_2_light
            - service: switch.turn_on
              target:
                entity_id: switch.giot_cn_1099597079_v6oodm_on_p_2_1
        # 如果状态一致，切换开关状态
        - conditions:
            - condition: template
              value_template: "{{ states_match }}"
          sequence:
            - service: light.toggle
              target:
                entity_id: light.nnleaf_cn_250150441_strips_s_2_light
            - service: switch.toggle
              target:
                entity_id: switch.giot_cn_1099597079_v6oodm_on_p_2_1

# ========== 双击按钮逻辑 - 切换light1亮度和模式 ==========
- alias: 书房 - nnleaf 切换亮度模式
  id: light_nnleaf_brightness
  trigger:
    - platform: state
      entity_id: event.090615_cn_blt_3_1gkcm9n48cc00_btsw1_double_click_e_2_1013
      not_from:
        - "unavailable"
        - "unknown"
      not_to:
        - "unavailable"
        - "unknown"
  action:
    # 切换到下一个模式（4种状态循环：橙色50%、80%、100%、模式252）
    - variables:
        current_mode: "{{ states('input_number.nnleaf_light_mode') | int }}"
        next_mode: "{{ (current_mode + 1) % 4 }}"
    - service: input_number.set_value
      target:
        entity_id: input_number.nnleaf_light_mode
      data:
        value: "{{ next_mode }}"
    - choose:
        # 模式0：橙色50%
        - conditions: "{{ next_mode == 0 }}"
          sequence:
            - service: number.set_value
              target:
                entity_id: number.nnleaf_cn_250150441_strips_current_scene_p_3_7
              data: { "value": 0 }
            - service: light.turn_on
              target:
                entity_id: light.nnleaf_cn_250150441_strips_s_2_light
              data:
                rgb_color: [255, 183, 124]
                brightness_pct: 50
        # 模式1：橙色80%
        - conditions: "{{ next_mode == 1 }}"
          sequence:
            - service: number.set_value
              target:
                entity_id: number.nnleaf_cn_250150441_strips_current_scene_p_3_7
              data: { "value": 0 }
            - service: light.turn_on
              target:
                entity_id: light.nnleaf_cn_250150441_strips_s_2_light
              data:
                rgb_color: [255, 183, 124]
                brightness_pct: 70
        # 模式2：橙色100%
        - conditions: "{{ next_mode == 2 }}"
          sequence:
            - service: number.set_value
              target:
                entity_id: number.nnleaf_cn_250150441_strips_current_scene_p_3_7
              data: { "value": 0 }
            - service: light.turn_on
              target:
                entity_id: light.nnleaf_cn_250150441_strips_s_2_light
              data:
                rgb_color: [255, 183, 124]
                brightness_pct: 90
        # 模式3：场景252
        - conditions: "{{ next_mode == 3 }}"
          sequence:
            - service: number.set_value
              target:
                entity_id: number.nnleaf_cn_250150441_strips_current_scene_p_3_7
              data: { "value": 252 }

# ========== 空气净化器自动关闭 ==========
- alias: 书房-空气净化器自动关闭
  id: study_air_purifier_auto_off
  description: 空气质量佳（空气优/空气良）持续超过30分钟且打印机非打印状态时，自动关闭空气净化器
  trigger:
    - platform: template
      value_template: >
        {{ states('sensor.zhimi_cn_706039150_rma3_air_quality_p_3_8') in ['空气优', '空气良'] }}
      for: "00:30:00"
  condition:
    # 确保净化器当前是开启状态
    - condition: state
      entity_id: switch.zhimi_cn_706039150_rma3_on_p_2_1
      state: "on"
    # 确保打印机不是打印状态
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.a1mini_0309aa490400817_print_status
          state: "running"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.zhimi_cn_706039150_rma3_on_p_2_1

# ========== 拓竹打印机打印时自动开启空气净化器 ==========
- alias: 书房-拓竹打印机打印时开启空气净化器
  id: study_3d_printer_air_purifier_auto_on
  description: 拓竹打印机状态变为打印中时，自动开启空气净化器
  trigger:
    - platform: state
      entity_id: sensor.a1mini_0309aa490400817_print_status
      to: "running"
      not_from:
        - "unavailable"
        - "unknown"
  condition:
    # 确保打印机状态为打印中
    - condition: state
      entity_id: sensor.a1mini_0309aa490400817_print_status
      state: "running"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.zhimi_cn_706039150_rma3_on_p_2_1

# ========== 空气污染持续超过30分钟自动开启空气净化器 ==========
- alias: 书房-空气污染30分钟自动开启空气净化器
  id: study_air_pollution_auto_on
  initial_state: false
  description: 书房空气污染状态（轻度污染及以上）持续超过30分钟且净化器关闭时，自动开启净化器并提醒
  trigger:
    - platform: template
      value_template: >
        {{ states('sensor.zhimi_cn_706039150_rma3_air_quality_p_3_8') in ['轻度污染', '中度污染', '重度污染', '严重污染'] }}
      for: "00:30:00"
  condition:
    # 只在净化器关闭状态下执行
    - condition: state
      entity_id: switch.zhimi_cn_706039150_rma3_on_p_2_1
      state: "off"
  action:
    # 开启空气净化器
    - service: switch.turn_on
      target:
        entity_id: switch.zhimi_cn_706039150_rma3_on_p_2_1
    # 播放提醒消息
    - service: script.xiaoai_speak
      data:
        text: >
          {% set air_quality = states('sensor.zhimi_cn_706039150_rma3_air_quality_p_3_8') %}
          书房空气{{ air_quality }}，已自动开启空气净化器
