# 厨房灯光自动化配置
# ========== 玄关无人移动超过30分钟且厨房灯开启超过25分钟 - 关闭厨房灯 ==========
- alias: 厨房 - 玄关无人30分钟且灯开启25分钟关灯
  id: light_kitchen_auto_off
  mode: restart
  description: 玄关无人移动超过30分钟（传感器维持在300超过1500秒），且厨房灯开启超过25分钟，关闭厨房灯
  trigger:
    - platform: state
      entity_id: sensor.linp_cn_blt_3_1kjgrp40ckg00_hs1bb2_no_motion_duration_p_2_1024
      to: "300"
      for: "00:30:00"
  condition:
    # 只在有人在家时触发
    - condition: state
      entity_id: binary_sensor.home_state
      state: "on"
    # 确保厨房灯当前是开启状态
    - condition: state
      entity_id: switch.giot_cn_1088662238_v6oodm_on_p_2_1
      state: 'on'
    # 检查厨房灯开启时间是否超过25分钟（1500秒）
    - condition: template
      value_template: >
        {% if states('switch.giot_cn_1088662238_v6oodm_on_p_2_1') not in ['unknown', 'unavailable', None] %}
          {% set kitchen_light = states.switch.giot_cn_1088662238_v6oodm_on_p_2_1 %}
          {% if kitchen_light.last_changed is defined %}
            {{ (now() - kitchen_light.last_changed).total_seconds() >= 1500 }}
          {% else %}
            False
          {% endif %}
        {% else %}
          False
        {% endif %}
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.giot_cn_1088662238_v6oodm_on_p_2_1

