# 玄关灯光自动化配置
# ========== 回家模式 - 开灯 ==========
- alias: 玄关 - 回家模式开灯
  id: light_entrance_home_mode
  mode: single
  description: 检测到"开门"事件且home_state为off时，开启筒灯和氛围灯；18-24点之间延迟5秒打开客厅灯带（优化：不等待home_state变为on，减少延迟）
  trigger:
    - platform: state
      entity_id: event.xiaomi_cn_1079257233_hub1_virtual_event_e_4_1
      not_from:
        - "unavailable"
        - "unknown"
      not_to:
        - "unavailable"
        - "unknown"
  condition:
    # 事件名称为"开门"
    - condition: template
      value_template: "{{ trigger.to_state.attributes.get('事件名称', '') == '开门' }}"
    # home_state为off，表示不在家状态（刚回家）
    - condition: state
      entity_id: binary_sensor.home_state
      state: "off"
    # home_state为off超过30秒，确保确实是从不在家状态回家
    # 添加安全检查，防止实体不存在或状态异常时出错
    - condition: template
      value_template: >
        {% if states('binary_sensor.home_state') not in ['unknown', 'unavailable', None] %}
          {% set home_state = states.binary_sensor.home_state %}
          {% if home_state.last_changed is defined %}
            {{ (now() - home_state.last_changed).total_seconds() >= 30 }}
          {% else %}
            False
          {% endif %}
        {% else %}
          False
        {% endif %}
  action:
    # 开启氛围灯
    - service: switch.turn_on
      target:
        entity_id: switch.giot_cn_1088542711_v6oodm_on_p_2_1
    # 开启筒灯（等待设备可用后延迟1秒开启）
    - wait_template: "{{ states('switch.linp_cn_1080373159_q3s2_on_p_3_1') not in ['unavailable', 'unknown'] }}"
      timeout: "00:00:10"
    - delay:
        seconds: 3
    - service: switch.turn_on
      target:
        entity_id: switch.linp_cn_1080373159_q3s2_on_p_3_1
    # 如果当前时间在18-24点之间，延迟5秒后打开客厅灯带
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ now().hour >= 18 }}"
          sequence:
            # 延迟5秒
            - delay:
                seconds: 1
            # 等待设备可用（设备启动有延迟）
            - wait_template: "{{ states('switch.lumi_cn_551288517_acn032_on_p_4_1') not in ['unavailable', 'unknown'] }}"
              timeout: "00:00:30"
            # 设备可用后，再延迟3秒开灯
            - delay:
                seconds: 3
            # 打开客厅灯带
            - service: switch.turn_on
              target:
                entity_id: switch.lumi_cn_551288517_acn032_on_p_4_1

# 领普人体传感器3 - 移动检测自动控制灯光
# ========== 检测到移动 - 开灯（常规模式）==========
- alias: 玄关 - 检测到移动开灯
  id: light_entrance_motion_detected
  mode: single
  description: 检测到移动时，且有人在家时，开启筒灯和氛围灯
  trigger:
    - platform: state
      entity_id: event.linp_cn_blt_3_1kjgrp40ckg00_hs1bb2_motion_detected_e_2_1008
      not_from:
        - "unavailable"
        - "unknown"
      not_to:
        - "unavailable"
        - "unknown"
  condition:
    # 只在有人在家时触发
    - condition: state
      entity_id: binary_sensor.home_state
      state: "on"
  action:
    # 开启筒灯
    - service: switch.turn_on
      target:
        entity_id: switch.linp_cn_1080373159_q3s2_on_p_3_1
    # 开启氛围灯
    - service: switch.turn_on
      target:
        entity_id: switch.giot_cn_1088542711_v6oodm_on_p_2_1

# ========== 无移动5分钟 - 关筒灯 ==========
- alias: 玄关 - 无移动5分钟关筒灯
  id: light_entrance_no_motion_5min
  mode: single
  description: 无移动5分钟后，关闭筒灯
  trigger:
    - platform: state
      entity_id: sensor.linp_cn_blt_3_1kjgrp40ckg00_hs1bb2_no_motion_duration_p_2_1024
      to: "300"
  condition:
    # 确保筒灯当前是开启状态
    - condition: state
      entity_id: switch.linp_cn_1080373159_q3s2_on_p_3_1
      state: 'on'
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.linp_cn_1080373159_q3s2_on_p_3_1

# ========== 无移动10分钟 - 关氛围灯 ==========
- alias: 玄关 - 无移动10分钟关氛围灯
  id: light_entrance_no_motion_10min
  mode: restart
  description: 无移动10分钟后（传感器维持在300超过300秒），关闭氛围灯
  trigger:
    - platform: state
      entity_id: sensor.linp_cn_blt_3_1kjgrp40ckg00_hs1bb2_no_motion_duration_p_2_1024
      to: "300"
      for: "00:10:00"
  condition:
    # 确保氛围灯当前是开启状态
    - condition: state
      entity_id: switch.giot_cn_1088542711_v6oodm_on_p_2_1
      state: 'on'
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.giot_cn_1088542711_v6oodm_on_p_2_1

