# 客厅灯光自动化配置
# 领普无线开关KS1Pro - 单击切换设备开关状态
# ========== 按键映射 ==========
# 按键1 -> switch.lumi_cn_551288517_acn032_on_p_2_1 (Aqara 妙控开关 S1E 主灯 左键)
# 按键2 -> switch.lumi_cn_551288517_acn032_on_p_3_1 (Aqara 妙控开关 S1E 筒灯 中键)
# 按键3 -> switch.lumi_cn_551288517_acn032_on_p_4_1 (Aqara 妙控开关 S1E 灯带 右键)
# 按键4 -> light.hyd_cn_672580633_pro2_s_3_light (米家智能晾衣机Pro 灯)

- alias: 客厅 - 无线开关切换设备状态
  id: light_living_switch_toggle
  mode: single
  description: 单击无线开关按键，反转对应设备的开关状态
  trigger:
    - platform: state
      entity_id: event.linp_cn_blt_3_1ie02q6jocg00_ks1bp_click_e_5_1012
      not_from:
        - "unavailable"
        - "unknown"
      not_to:
        - "unavailable"
        - "unknown"
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.attributes.get('event_type') == '单击' }}"
  action:
    - variables:
        # 从状态属性中获取按键类型
        button_type: "{{ trigger.to_state.attributes.get('按键类型', trigger.to_state.attributes.get('button_type', trigger.to_state.attributes.get('key', ''))) | string }}"
        button_num: "{{ button_type | int(0) }}"
    - choose:
        # 按键1 - 主灯 左键
        - conditions:
            - condition: template
              value_template: "{{ button_type == '1' or button_num == 1 }}"
          sequence:
            - service: switch.toggle
              target:
                entity_id: switch.lumi_cn_551288517_acn032_on_p_2_1
        # 按键2 - 筒灯 中键
        - conditions:
            - condition: template
              value_template: "{{ button_type == '2' or button_num == 2 }}"
          sequence:
            - service: switch.toggle
              target:
                entity_id: switch.lumi_cn_551288517_acn032_on_p_3_1
        # 按键3 - 灯带 右键
        - conditions:
            - condition: template
              value_template: "{{ button_type == '3' or button_num == 3 }}"
          sequence:
            - service: switch.toggle
              target:
                entity_id: switch.lumi_cn_551288517_acn032_on_p_4_1
        # 按键4 - 米家智能晾衣机Pro 灯
        - conditions:
            - condition: template
              value_template: "{{ button_type == '4' or button_num == 4 }}"
          sequence:
            - service: light.toggle
              target:
                entity_id: light.hyd_cn_672580633_pro2_s_3_light

# ========== 双击事件 - 日志记录 ==========
- alias: 客厅 - 无线开关双击事件日志
  id: light_living_double_click_log
  mode: single
  description: 记录无线开关双击事件的 payload 明细到 logbook
  trigger:
    - platform: state
      entity_id: event.linp_cn_blt_3_1ie02q6jocg00_ks1bp_double_click_e_5_1013
      not_from:
        - "unavailable"
        - "unknown"
      not_to:
        - "unavailable"
        - "unknown"
  action:
    - service: logbook.log
      data:
        name: 无线开关双击事件
        message: "Payload明细: {{ trigger.to_state.attributes | to_json }}"
        entity_id: automation.light_living_double_click_log

# ========== 双击事件 - 按键1切换灯1模式 ==========
- alias: 客厅 - 按键1双击切换灯1模式
  id: light_living_button1_double_click_mode
  mode: single
  description: 按键1双击时，切换灯1亮度模式（月光、休闲、会客循环）
  trigger:
    - platform: state
      entity_id: event.linp_cn_blt_3_1ie02q6jocg00_ks1bp_double_click_e_5_1013
      not_from:
        - "unavailable"
        - "unknown"
      not_to:
        - "unavailable"
        - "unknown"
  condition:
    - condition: template
      value_template: >
        {% set button_type = trigger.to_state.attributes.get('按键类型', trigger.to_state.attributes.get('button_type', trigger.to_state.attributes.get('key', ''))) | string %}
        {% set button_num = button_type | int(0) %}
        {{ button_type == '1' or button_num == 1 }}
  action:
    - variables:
        # 获取当前灯1的effect状态
        current_effect: "{{ state_attr('light.ftd_cn_1087033247_ftdlmp_s_2_light', 'effect') }}"
        # 计算下一个模式（月光、休闲、会客循环）
        next_mode: >
          {% set modes = ["月光（夜间）模式", "休闲模式", "会客模式"] %}
          {% set current = current_effect %}
          {% set current_idx = 0 %}
          {% if current == "月光（夜间）模式" %}
            {% set current_idx = 0 %}
          {% elif current == "休闲模式" %}
            {% set current_idx = 1 %}
          {% elif current == "会客模式" %}
            {% set current_idx = 2 %}
          {% endif %}
          {% set next_idx = (current_idx + 1) % 3 %}
          {{ modes[next_idx] }}
    - service: light.turn_on
      target:
        entity_id: light.ftd_cn_1087033247_ftdlmp_s_2_light
      data:
        effect: "{{ next_mode }}"

# ========== 长按事件 - 日志记录 ==========
- alias: 客厅 - 无线开关长按事件日志
  id: light_living_long_press_log
  mode: single
  description: 记录无线开关长按事件的 payload 明细到 logbook
  trigger:
    - platform: state
      entity_id: event.linp_cn_blt_3_1ie02q6jocg00_ks1bp_long_press_e_5_1014
      not_from:
        - "unavailable"
        - "unknown"
      not_to:
        - "unavailable"
        - "unknown"
  action:
    - service: logbook.log
      data:
        name: 无线开关长按事件
        message: "Payload明细: {{ trigger.to_state.attributes | to_json }}"
        entity_id: automation.light_living_long_press_log

